# Generated by Django 3.0.2 on 2020-02-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20200202_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='paymentID',
        ),
        migrations.CreateModel(
            name='ProductOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', models.ManyToManyField(to='shop.Cart')),
            ],
        ),
    ]
